'use strict';

const path = require('path');
const environment = require('./environment');

/** Backend package root (food-supply-chain/backend) */
const BACKEND_ROOT = path.resolve(__dirname, '../..');

/** Absolute root for peer organization crypto materials */
const PEER_ORGS_ROOT = path.resolve(BACKEND_ROOT, environment.fabricPeerOrgPath);

/**
 * Org → peer endpoint and MSP mapping for Fabric Gateway connections.
 * Cert/key paths point at User1 identities generated by the network scripts.
 */
const ORG_CONFIG = Object.freeze({
  FarmOrgMSP: {
    mspId: 'FarmOrgMSP',
    role: 'FARM',
    peerEndpoint: 'localhost:7051',
    peerHostAlias: 'peer0.farm.foodchain.com',
    domain: 'farm.foodchain.com',
    tlsCertPath: path.join(
      PEER_ORGS_ROOT,
      'farm.foodchain.com',
      'peers',
      'peer0.farm.foodchain.com',
      'tls',
      'ca.crt'
    ),
    certPath: path.join(
      PEER_ORGS_ROOT,
      'farm.foodchain.com',
      'users',
      'User1@farm.foodchain.com',
      'msp',
      'signcerts'
    ),
    keyPath: path.join(
      PEER_ORGS_ROOT,
      'farm.foodchain.com',
      'users',
      'User1@farm.foodchain.com',
      'msp',
      'keystore'
    ),
  },
  ProcessorOrgMSP: {
    mspId: 'ProcessorOrgMSP',
    role: 'PROCESSOR',
    peerEndpoint: 'localhost:9051',
    peerHostAlias: 'peer0.processor.foodchain.com',
    domain: 'processor.foodchain.com',
    tlsCertPath: path.join(
      PEER_ORGS_ROOT,
      'processor.foodchain.com',
      'peers',
      'peer0.processor.foodchain.com',
      'tls',
      'ca.crt'
    ),
    certPath: path.join(
      PEER_ORGS_ROOT,
      'processor.foodchain.com',
      'users',
      'User1@processor.foodchain.com',
      'msp',
      'signcerts'
    ),
    keyPath: path.join(
      PEER_ORGS_ROOT,
      'processor.foodchain.com',
      'users',
      'User1@processor.foodchain.com',
      'msp',
      'keystore'
    ),
  },
  DistributorOrgMSP: {
    mspId: 'DistributorOrgMSP',
    role: 'DISTRIBUTOR',
    peerEndpoint: 'localhost:11051',
    peerHostAlias: 'peer0.distributor.foodchain.com',
    domain: 'distributor.foodchain.com',
    tlsCertPath: path.join(
      PEER_ORGS_ROOT,
      'distributor.foodchain.com',
      'peers',
      'peer0.distributor.foodchain.com',
      'tls',
      'ca.crt'
    ),
    certPath: path.join(
      PEER_ORGS_ROOT,
      'distributor.foodchain.com',
      'users',
      'User1@distributor.foodchain.com',
      'msp',
      'signcerts'
    ),
    keyPath: path.join(
      PEER_ORGS_ROOT,
      'distributor.foodchain.com',
      'users',
      'User1@distributor.foodchain.com',
      'msp',
      'keystore'
    ),
  },
  RetailOrgMSP: {
    mspId: 'RetailOrgMSP',
    role: 'STORE_ADMIN',
    peerEndpoint: 'localhost:13051',
    peerHostAlias: 'peer0.retail.foodchain.com',
    domain: 'retail.foodchain.com',
    tlsCertPath: path.join(
      PEER_ORGS_ROOT,
      'retail.foodchain.com',
      'peers',
      'peer0.retail.foodchain.com',
      'tls',
      'ca.crt'
    ),
    certPath: path.join(
      PEER_ORGS_ROOT,
      'retail.foodchain.com',
      'users',
      'User1@retail.foodchain.com',
      'msp',
      'signcerts'
    ),
    keyPath: path.join(
      PEER_ORGS_ROOT,
      'retail.foodchain.com',
      'users',
      'User1@retail.foodchain.com',
      'msp',
      'keystore'
    ),
  },
  AuditorOrgMSP: {
    mspId: 'AuditorOrgMSP',
    role: 'AUDITOR',
    peerEndpoint: 'localhost:15051',
    peerHostAlias: 'peer0.auditor.foodchain.com',
    domain: 'auditor.foodchain.com',
    tlsCertPath: path.join(
      PEER_ORGS_ROOT,
      'auditor.foodchain.com',
      'peers',
      'peer0.auditor.foodchain.com',
      'tls',
      'ca.crt'
    ),
    certPath: path.join(
      PEER_ORGS_ROOT,
      'auditor.foodchain.com',
      'users',
      'User1@auditor.foodchain.com',
      'msp',
      'signcerts'
    ),
    keyPath: path.join(
      PEER_ORGS_ROOT,
      'auditor.foodchain.com',
      'users',
      'User1@auditor.foodchain.com',
      'msp',
      'keystore'
    ),
  },
});

/** Demo / local API users mapped to application roles and Fabric MSP identities */
const DEMO_USERS = Object.freeze({
  'farm@foodchain.local': {
    email: 'farm@foodchain.local',
    name: 'Farm Operator',
    role: 'FARM',
    mspId: 'FarmOrgMSP',
  },
  'processor@foodchain.local': {
    email: 'processor@foodchain.local',
    name: 'Processor Operator',
    role: 'PROCESSOR',
    mspId: 'ProcessorOrgMSP',
  },
  'distributor@foodchain.local': {
    email: 'distributor@foodchain.local',
    name: 'Distributor Operator',
    role: 'DISTRIBUTOR',
    mspId: 'DistributorOrgMSP',
  },
  'store@foodchain.local': {
    email: 'store@foodchain.local',
    name: 'Store Administrator',
    role: 'STORE_ADMIN',
    mspId: 'RetailOrgMSP',
  },
  'auditor@foodchain.local': {
    email: 'auditor@foodchain.local',
    name: 'Supply Chain Auditor',
    role: 'AUDITOR',
    mspId: 'AuditorOrgMSP',
  },
});

const ROLE_TO_MSP = Object.freeze({
  FARM: 'FarmOrgMSP',
  PROCESSOR: 'ProcessorOrgMSP',
  DISTRIBUTOR: 'DistributorOrgMSP',
  STORE_ADMIN: 'RetailOrgMSP',
  AUDITOR: 'AuditorOrgMSP',
});

const ALL_ROLES = Object.freeze([
  'FARM',
  'PROCESSOR',
  'DISTRIBUTOR',
  'STORE_ADMIN',
  'AUDITOR',
]);

function getOrgConfig(mspId) {
  const config = ORG_CONFIG[mspId];
  if (!config) {
    const err = new Error(`Unknown organization MSP: ${mspId}`);
    err.statusCode = 400;
    err.code = 'UNKNOWN_MSP';
    throw err;
  }
  return config;
}

function getUserByEmail(email) {
  if (!email) return null;
  return DEMO_USERS[String(email).trim().toLowerCase()] || null;
}

module.exports = {
  PEER_ORGS_ROOT,
  ORG_CONFIG,
  DEMO_USERS,
  ROLE_TO_MSP,
  ALL_ROLES,
  getOrgConfig,
  getUserByEmail,
  channelName: environment.fabricChannelName,
  chaincodeName: environment.fabricChaincodeName,
};
